const images = {
    darkLogo: require('./dark-logo.svg').default,
    lightLogo: require('./light-logo.svg').default,
    lamasadImg: require('./llamasad.jpg').default,
    loginRegisterBG: require('./polifolli-office-fin.jpg').default,
    logo: require('./logo.svg').default,
    llama: require('./Llamasad.png').default,
    llamaBones: require('./bonellama.png').default,
    imgTest: require('./test.png').default,
    avatar: require('./avatar.png').default,
    docxIcon: require('./docx_icon.png').default,
    pdfIcon: require('./pdf-icon.png').default,
    pngIcon: require('./png_icon.png').default,
    gsapIcon: require('./greensock-gsap-icon.png').default,
    reactIcon: require('./React-icon.svg.png').default,
    reduxIcon: require('./redux-icon.png').default,
    postgresIcon: require('./Postgresql-icon.png').default,
    mysqlIcon: require('./mysql-icon.png').default,
    mongodbIcon: require('./mongodb-icon.svg').default,
    nodejsIcon: require('./node-js-icon.png').default,
    nextjsIcon: require('./nextjs-icon.png').default,
    linuxIcon: require('./linux-icon.png').default,
    socketIcon: require('./Socket-io.svg.png').default,
    skillPage: require('./skill-page.png').default,
    hallweenIcon: require('./halloween-icon.jpeg').default,
    catIcon: require('./cat_icon.png').default,
    showcasePage: require('./showcase-page.png').default,
    tManagerPage: require('./task-manager.png').default,
    hpnyGame: require('./hpny-game.png').default,
};

export default images;
