import type { Metadata } from 'next';
import classNames from 'classnames';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/layout/header';
import ThemeColorWraper from '@/components/layout/theme-color-wrapper';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Lamast',
    description: 'Generated by create next app',
    icons: { icon: '/icon.svg' },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeColorWraper>
                <Header />
                {children}
                </ThemeColorWraper>
            </body>
        </html>
    );
}
