import type { Metadata } from 'next';
import classNames from 'classnames';
import Image from 'next/image';
import { Roboto } from 'next/font/google';
import { headers, cookies } from 'next/headers';
import './globals.css';
import Header from '@/components/layout/header';
import ThemeColorWraper from '@/components/layout/theme-color-wrapper';
import { Providers as StoreProvider } from '@/lib/provide';
import PluginInit from '@/components/plugin-init';

const roboto = Roboto({
    weight: ['300', '400', '500', '700'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Llamasad',
    description: 'Generated by create next app',
    icons: { icon: '/logo-llama.svg' },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    const cookieStore = cookies();
    const theme = cookieStore.get('theme');
    return (
        <html lang="en">
            <body className={roboto.className} theme-data={theme?.value}>
                <StoreProvider>
                    <PluginInit>
                        <ThemeColorWraper>
                            <Header />
                            {children}
                        </ThemeColorWraper>
                    </PluginInit>
                </StoreProvider>
            </body>
        </html>
    );
}
