import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { cookies } from 'next/headers';
import '../globals.css';
import Header from '@/components/layout/header';
import ThemeColorWraper from '@/components/wrapper-components/theme-color-wrapper';
import { Providers as StoreProvider } from '@/lib/provide';
import PluginInit from '@/components/plugin-init';
import { useTranslations } from 'next-intl';
import LoadingLineProvider from '@/components/provider/loading-bar-provider';
const roboto = Roboto({
    weight: ['300', '400', '500', '700'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
});
export const metadata: Metadata = {
    title: 'Llamasad',
    description: 'Generated by create next app',
    icons: { icon: '/logo-llama.svg' },
};

export default function RootLayout({ children, params }: { children: React.ReactNode; params: { locale: string } }) {
    const cookieStore = cookies();
    const theme = cookieStore.get('theme');
    // unstable_setRequestLocale(params.locale);

    // const t = useTranslations('Index');
    // console.log(t('title'));
    return (
        <html lang={params.locale}>
            <body className={roboto.className} theme-data={theme?.value}>
                <StoreProvider>
                    <PluginInit>
                        <ThemeColorWraper>
                            <LoadingLineProvider>
                                <>
                                    <Header />
                                    <div className="mb:w-mb-body tl:w-tl-body lt:w-lt-body dt:w-dt-body mx-auto">
                                        {children}
                                    </div>
                                </>
                            </LoadingLineProvider>
                        </ThemeColorWraper>
                    </PluginInit>
                </StoreProvider>
            </body>
        </html>
    );
}
