/* Core */
import { createSlice } from '@reduxjs/toolkit';

/* Instruments */
const initialState: ThemeSliceState = {
    mode: 'light',
};

export const themeSlice = createSlice({
    name: 'theme',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        toggle: (state) => {
            // Redux Toolkit allows us to write "mutating" logic in reducers. It
            // doesn't actually mutate the state because it uses the Immer library,
            // which detects changes to a "draft state" and produces a brand new
            // immutable state based off those changes
            state.mode = state.mode === 'light' ? 'dark' : 'light';
        },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
});

/* Types */
export type theme = 'light' | 'dark';
export interface ThemeSliceState {
    mode: theme;
}
export * from './selector';
